[workspace]
members = [
    "src/pd-codegen",
    "src/pd-db",
    "src/pd-ds",
    "src/pd-ide",
    "src/pd-ir",
    "src/pd-lex",
    "src/pd-ls",
    "src/pd-parse",
    "src/pd-syntax",
    "src/pd-vfs",
]
