[package]
name = "pd-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
expect-test = "1"
rowan = "0.15.0"

[dependencies.pd-ds]
path = "../pd-ds/"

[dependencies.pd-lex]
path = "../pd-lex/"

[dependencies.pd-syntax]
path = "../pd-syntax/"
