[package]
name = "pd-ir"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1"
salsa = "0.17.0-pre.2"

[dependencies.pd-parse]
path = "../pd-parse"

[dependencies.pd-syntax]
path = "../pd-syntax"

[dependencies.pd-vfs]
path = "../pd-vfs"
