[package]
name = "pd-lex"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc_lexer = { version = "727.0.0", package = "rustc-ap-rustc_lexer" }
text-size = "1"

[dependencies.pd-syntax]
path = "../pd-syntax"