[package]
name = "pd-ide"
version = "0.1.0"
edition = "2021"

[dependencies]
salsa = "0.17.0-pre.2"
anyhow = "1"
indexvec = "0.5"

[dependencies.pd-parse]
path = "../pd-parse"

[dependencies.pd-syntax]
path = "../pd-syntax"

[dependencies.pd-db]
path = "../pd-db"
